/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 8.1
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasilKurang = new javax.swing.JButton();
        hasilKali = new javax.swing.JButton();
        hasilBagi = new javax.swing.JButton();
        hasilTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bilangan1 = new javax.swing.JTextField();
        bilangan2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        hasilKurang.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hasilKurang.setText("-");
        hasilKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilKurangActionPerformed(evt);
            }
        });
        getContentPane().add(hasilKurang);
        hasilKurang.setBounds(280, 190, 70, 60);

        hasilKali.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hasilKali.setText("X");
        hasilKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilKaliActionPerformed(evt);
            }
        });
        getContentPane().add(hasilKali);
        hasilKali.setBounds(40, 190, 70, 60);

        hasilBagi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hasilBagi.setText(":");
        hasilBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilBagiActionPerformed(evt);
            }
        });
        getContentPane().add(hasilBagi);
        hasilBagi.setBounds(120, 190, 70, 60);

        hasilTambah.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hasilTambah.setText("+");
        hasilTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTambahActionPerformed(evt);
            }
        });
        getContentPane().add(hasilTambah);
        hasilTambah.setBounds(200, 190, 70, 60);

        jLabel1.setText("Bilangan 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 80, 14);

        jLabel2.setText("Bilangan 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 80, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kalkulator Sderhana");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 20, 150, 17);
        getContentPane().add(bilangan1);
        bilangan1.setBounds(170, 60, 150, 30);

        bilangan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilangan2ActionPerformed(evt);
            }
        });
        getContentPane().add(bilangan2);
        bilangan2.setBounds(170, 110, 150, 30);

        jLabel4.setText("Operator");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 160, 70, 14);

        jLabel5.setText("Hasil");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 300, 50, 14);

        hasil.setEditable(false);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(150, 280, 190, 60);

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 350);

        setBounds(0, 0, 409, 394);
    }// </editor-fold>//GEN-END:initComponents

    private void bilangan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilangan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilangan2ActionPerformed

    private void hasilKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilKaliActionPerformed
        int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(bilangan2.getText());
        int hasilkali = bil1*bil2;
        
        hasil.setText(String.valueOf(hasilkali));
    }//GEN-LAST:event_hasilKaliActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        
    }//GEN-LAST:event_hasilActionPerformed

    private void hasilBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilBagiActionPerformed
        double bil1 = Double.parseDouble(bilangan1.getText());
        double bil2 = Double.parseDouble(bilangan2.getText());
        double hasilbagi = bil1/bil2;
        
        hasil.setText(String.valueOf(hasilbagi));
    }//GEN-LAST:event_hasilBagiActionPerformed

    private void hasilTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTambahActionPerformed
        int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(bilangan2.getText());
        int hasiltambah = bil1+bil2;
        
        hasil.setText(String.valueOf(hasiltambah));
    }//GEN-LAST:event_hasilTambahActionPerformed

    private void hasilKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilKurangActionPerformed
        int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(bilangan2.getText());
        int hasilkurang = bil1-bil2;
        
        hasil.setText(String.valueOf(hasilkurang));
    }//GEN-LAST:event_hasilKurangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bilangan1;
    private javax.swing.JTextField bilangan2;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hasilBagi;
    private javax.swing.JButton hasilKali;
    private javax.swing.JButton hasilKurang;
    private javax.swing.JButton hasilTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
